### ISSUE TITLE
NumbaNotImplementedError for the get_residuals command after updating species to use Sonora Diamondback.

### ISSUE THREAD

**Issue by cianotoole11** [tomasstolker/species#127] opened 2024-11-19 12:37 UTC
Hi there,

Thanks so much for installing Sonora Diamondback into species! I've just encountered this error since I've updated species so i could access Diamondback. I've looked at everything I can and I'm struggling to see how or why I was able to use get_residuals before updating and now can't use it at all for any of the models, not just Diamondback. I'm just wondering if you have any idea why this may be happening or if you've any experience with these type of errors.

The main error at the end of this is: **NumbaValueError: Unsupported array dtype: >f8**

Thanks again for taking the time to install Diamondback,
Kind regards,
Cian

NumbaNotImplementedError                  Traceback (most recent call last)
File ~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:246, in _typeof_ndarray(val, c)
    [245](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:245) try:
--> [246](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:246)     dtype = numpy_support.from_dtype(val.dtype)
    [247](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:247) except errors.NumbaNotImplementedError:

File ~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/np/numpy_support.py:114, in from_dtype(dtype)
    [112](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/np/numpy_support.py:112)         return types.NestedArray(subtype, dtype.shape)
--> [114](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/np/numpy_support.py:114) raise errors.NumbaNotImplementedError(dtype)

NumbaNotImplementedError: >f8

During handling of the above exception, another exception occurred:

NumbaValueError                           Traceback (most recent call last)
Cell In[75], [line 25](vscode-notebook-cell:?execution_count=75&line=25)
     [17](vscode-notebook-cell:?execution_count=75&line=17) objectbox = update_objectbox(objectbox=objectbox, model_param=best)
     [19](vscode-notebook-cell:?execution_count=75&line=19) # residuals = get_residuals(datatype='model',
     [20](vscode-notebook-cell:?execution_count=75&line=20) #                           spectrum='sonora-bobcat',
     [21](vscode-notebook-cell:?execution_count=75&line=21) #                           parameters=best,
     [22](vscode-notebook-cell:?execution_count=75&line=22) #                           objectbox=objectbox,
     [23](vscode-notebook-cell:?execution_count=75&line=23) #                           inc_spec=True)
---> [25](vscode-notebook-cell:?execution_count=75&line=25) residuals = get_residuals(tag='2M0036+18VLA',
     [26](vscode-notebook-cell:?execution_count=75&line=26)                           datatype='model',
     [27](vscode-notebook-cell:?execution_count=75&line=27)                           spectrum='bt-settl',
     [28](vscode-notebook-cell:?execution_count=75&line=28)                           parameters=best,
     [29](vscode-notebook-cell:?execution_count=75&line=29)                           objectbox=objectbox,
     [30](vscode-notebook-cell:?execution_count=75&line=30)                           inc_phot=False,
     [31](vscode-notebook-cell:?execution_count=75&line=31)                           inc_spec=True)
     [33](vscode-notebook-cell:?execution_count=75&line=33) # residuals = get_residuals(tag='2M0036+18VLA',
     [34](vscode-notebook-cell:?execution_count=75&line=34) #                           spectrum='bt-settl',
     [35](vscode-notebook-cell:?execution_count=75&line=35) #                           parameters=best,
   (...)
     [61](vscode-notebook-cell:?execution_count=75&line=61) #                            filters=objectbox.filters,
     [62](vscode-notebook-cell:?execution_count=75&line=62) #                            parameters=best)

File ~/species/species/util/fit_util.py:516, in get_residuals(tag, parameters, objectbox, inc_phot, inc_spec, radtrans, datatype, spectrum)
    [504](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:504)         model_spec = create_box(
    [505](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:505)             boxtype="model",
    [506](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:506)             model=model_name,
   (...)
    [510](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:510)             quantity="flux",
    [511](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:511)         )
    [513](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:513)     else:
    [514](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:514)         # Single object
--> [516](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:516)         model_spec = readmodel.get_model(
    [517](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:517)             parameters,
    [518](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:518)             spec_res=spec_res,
    [519](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:519)             wavel_resample=wl_new,
    [520](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:520)         )
    [522](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:522)     flux_new = model_spec.flux
    [524](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/util/fit_util.py:524) data_spec = objectbox.spectrum[key][0]

File ~/species/species/read/read_model.py:978, in get_model(self, model_param, spec_res, wavel_resample, magnitude, fast_rot_broad, ext_filter, **kwargs)
    [975](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/read/read_model.py:975) # Resample the spectrum
    [977](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/read/read_model.py:977) if wavel_resample is not None:
--> [978](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/read/read_model.py:978)     model_box.flux = spectres_numba(
    [979](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/read/read_model.py:979)         wavel_resample,
    [980](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/read/read_model.py:980)         model_box.wavelength,
    [981](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/read/read_model.py:981)         model_box.flux,
    [982](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/read/read_model.py:982)         spec_errs=None,
    [983](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/read/read_model.py:983)         fill=np.nan,
    [984](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/read/read_model.py:984)         verbose=True,
    [985](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/read/read_model.py:985)     )
    [987](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/read/read_model.py:987)     model_box.wavelength = wavel_resample
    [989](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/species/species/read/read_model.py:989) # Convert flux to magnitude

File ~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/spectres/spectral_resampling_numba.py:28, in spectres_numba(new_wavs, spec_wavs, spec_fluxes, spec_errs, fill, verbose)
     [22](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/spectres/spectral_resampling_numba.py:22) def spectres_numba(new_wavs, spec_wavs, spec_fluxes, spec_errs=None, fill=0,
     [23](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/spectres/spectral_resampling_numba.py:23)                    verbose=True):
     [24](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/spectres/spectral_resampling_numba.py:24)     """
     [25](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/spectres/spectral_resampling_numba.py:25)     Wrapper function to preserve interface when using Numba
     [26](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/spectres/spectral_resampling_numba.py:26)     """
---> [28](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/spectres/spectral_resampling_numba.py:28)     new_fluxes, new_errs = spnumba(new_wavs, spec_wavs, spec_fluxes,
     [29](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/spectres/spectral_resampling_numba.py:29)                                    spec_errs=spec_errs, fill=fill,
     [30](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/spectres/spectral_resampling_numba.py:30)                                    verbose=verbose)
     [32](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/spectres/spectral_resampling_numba.py:32)     # If errors not supplied, only return the fluxes not array of zeros
     [33](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/spectres/spectral_resampling_numba.py:33)     if spec_errs is None:

File ~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/dispatcher.py:688, in _DispatcherBase.typeof_pyval(self, val)
    [685](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/dispatcher.py:685) # Not going through the resolve_argument_type() indirection
    [686](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/dispatcher.py:686) # can save a couple µs.
    [687](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/dispatcher.py:687) try:
--> [688](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/dispatcher.py:688)     tp = typeof(val, Purpose.argument)
    [689](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/dispatcher.py:689) except ValueError:
    [690](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/dispatcher.py:690)     tp = types.pyobject

File ~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:33, in typeof(val, purpose)
     [31](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:31) # Note the behaviour for Purpose.argument must match _typeof.c.
     [32](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:32) c = _TypeofContext(purpose)
---> [33](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:33) ty = typeof_impl(val, c)
     [34](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:34) if ty is None:
     [35](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:35)     msg = _termcolor.errmsg(
     [36](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:36)         f"Cannot determine Numba type of {type(val)}")

File ~/anaconda3/envs/pymc-a0/lib/python3.10/functools.py:889, in singledispatch.<locals>.wrapper(*args, **kw)
    [885](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/functools.py:885) if not args:
    [886](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/functools.py:886)     raise TypeError(f'{funcname} requires at least '
    [887](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/functools.py:887)                     '1 positional argument')
--> [889](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/functools.py:889) return dispatch(args[0].__class__)(*args, **kw)

File ~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:248, in _typeof_ndarray(val, c)
    [246](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:246)     dtype = numpy_support.from_dtype(val.dtype)
    [247](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:247) except errors.NumbaNotImplementedError:
--> [248](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:248)     raise errors.NumbaValueError(f"Unsupported array dtype: {val.dtype}")
    [249](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:249) layout = numpy_support.map_layout(val)
    [250](https://file+.vscode-resource.vscode-cdn.net/Users/cianotoole/Documents/HST/Export/~/anaconda3/envs/pymc-a0/lib/python3.10/site-packages/numba/core/typing/typeof.py:250) readonly = not val.flags.writeable

NumbaValueError: Unsupported array dtype: >f8

**Comment by tomasstolker** [comment] 2024-11-19 12:51
Hi Cian,

Hmmm, if I understand correctly, it seems that there is an issue with the data type of the array with wavelengths that is used for the resampling. Those wavelengths come from the spectra that you have added to the database with `add_object`.

Could there somehow be an "issue" with those spectra? E.g. the format of the values in the data file from which the spectra are read?

Perhaps you can try to first read in the spectra (e.g. with `np.loadtxt`), then check the `dtype` attribute of the array to make sure it is a regular float, and then provide the array directly as input to `add_object`.

See here for passing an array directly to the `spectrum` parameter of `add_object`:
https://species.readthedocs.io/en/latest/species.data.html#species.data.database.Database.add_object

Let me know if anything is unclear and/or you need further help!

**Comment by cianotoole11** [comment] 2024-11-19 12:57
Hi Tomas,

I'll check it there now again, but prior to updating species in order to access Diamondback, I had no issue with the _get_residuals_.  I loaded my data by converting it into a fits file and then passing that through the '_spectrum=_' parameter of _add_object_. Was there anything changed to the add_object command since the update of Diamondback? This has only become an issue since I've updated it.

Thanks again for getting back to me so quickly!

**Comment by tomasstolker** [comment] 2024-11-19 13:02
Nothing changed in `add_object`, but I did change the resampling in `ReadModel`, which is used by `get_residuals`, to `spectres`. That last function uses numba, which does not seem to like the datatype of the wavelengths. Not sure why, perhaps there is a NaN or something in the spectrum array?

**Comment by cianotoole11** [comment] 2024-11-19 13:15
Hi Tomas, I've checked my fits file, all it contains is ~80 wavelength/flux/flux error/ points, without nans. It does say however at the end _**dtype='>f8'**_. It's the same as before the diamondback update, is there a particular datatype you recommend me converting it to?

**Comment by tomasstolker** [comment] 2024-11-19 13:41
Thanks for testing, the issue is that the FITS format uses big-endian byte-order, whereas most machines use little-endian. Could you pull from Github? The fix applies a byteswap when data is read from a FITS file. Could you pull from Github and test if it works? Or passing the array directly should indeed also work.

**Comment by tomasstolker** [comment] 2024-11-27 10:42
Closing this issue because it has been resolved.

**Closed as completed by tomasstolker** 2024-11-27 10:42 UTC
Labels: type: bug
